"""add digital twin strategy tables

Revision ID: 001d51d7135f
Revises: fec0468eb1aa
Create Date: 2026-08-14 15:13:33.625049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001d51d7135f'
down_revision = 'fec0468eb1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_plan',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_strategy_plan_year')
    )
    with op.batch_alter_table('strategy_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_plan_year'), ['year'], unique=False)

    op.create_table('strategy_assessment',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'dimension', name='uq_assessment_plan_dimension')
    )
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_assessment_plan_id'), ['plan_id'], unique=False)

    op.create_table('strategy_evidence',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_evidence_plan_id'), ['plan_id'], unique=False)

    # 자동 생성이 dt2_agent_runs 의 ix_dt2_agent_runs_created_at 삭제를 함께
    # 넣었으나 제거했다. 이 마이그레이션과 무관한 기존 드리프트이고, 그대로
    # 적용하면 관계없는 테이블의 인덱스가 조용히 사라진다.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_evidence_plan_id'))
        batch_op.drop_index('ix_evidence_target')

    op.drop_table('strategy_evidence')
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_assessment_plan_id'))

    op.drop_table('strategy_assessment')
    with op.batch_alter_table('strategy_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_plan_year'))

    op.drop_table('strategy_plan')
    # ### end Alembic commands ###
