"""replace link_system with link_system_from and link_system_to

Revision ID: 037f84e8184e
Revises: a6d233565613
Create Date: 2026-02-13 13:00:11.005552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037f84e8184e'
down_revision = 'a6d233565613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_system_from', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('link_system_to', sa.String(length=200), nullable=True))
        batch_op.drop_column('link_system')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_system', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('link_system_to')
        batch_op.drop_column('link_system_from')

    # ### end Alembic commands ###
