"""add test_item_detail to dt_reference_tasks

Revision ID: 08ce5ac029ba
Revises: 63942d35f81f
Create Date: 2026-02-23 13:10:06.406096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ce5ac029ba'
down_revision = '63942d35f81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_reference_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_item_detail', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_reference_tasks', schema=None) as batch_op:
        batch_op.drop_column('test_item_detail')

    # ### end Alembic commands ###
