"""add license_nature to sw_resources

Revision ID: 090e17b9c93f
Revises: c96435410d5d
Create Date: 2026-03-23 21:46:13.580725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090e17b9c93f'
down_revision = 'c96435410d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_nature', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.drop_column('license_nature')

    # ### end Alembic commands ###
