"""add category column to spdm_modules

Revision ID: 118d4fd00e19
Revises: 81f93d9c46e6
Create Date: 2026-02-11 14:55:30.733667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118d4fd00e19'
down_revision = '81f93d9c46e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
