"""add system_type column to spdm_modules

Revision ID: 178a6dd05474
Revises: 118d4fd00e19
Create Date: 2026-02-11 15:11:29.200923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178a6dd05474'
down_revision = '118d4fd00e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.drop_column('system_type')

    # ### end Alembic commands ###
