"""Add thumbnail to test_methods

Revision ID: 2b6231034a01
Revises: f8a57966cc0d
Create Date: 2026-01-04 21:10:01.606094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6231034a01'
down_revision = 'f8a57966cc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_methods', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
