"""Add is_discussion to BoardCategory

Revision ID: 3823dc803c06
Revises: 369ad82da43f
Create Date: 2025-12-09 16:52:05.550418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3823dc803c06'
down_revision = '369ad82da43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_discussion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_categories', schema=None) as batch_op:
        batch_op.drop_column('is_discussion')

    # ### end Alembic commands ###
