"""Add color column to performance_categories

Revision ID: 3d21164fd6d0
Revises: cc39fc7ad7e1
Create Date: 2025-12-08 10:18:45.614340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d21164fd6d0'
down_revision = 'cc39fc7ad7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_categories', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
