"""Add TechLevelData model

Revision ID: 4212dfd4fc3a
Revises: ab9962929b95
Create Date: 2025-12-20 09:41:22.588416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4212dfd4fc3a'
down_revision = 'ab9962929b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_level_data',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('components', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('level_options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('category_options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('business_unit_options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_type_options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_level_data')
    # ### end Alembic commands ###
