"""change sw_resources category to json array

Revision ID: 4c7916eece9a
Revises: 9e9513dc80b8
Create Date: 2026-03-23 20:51:30.206160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7916eece9a'
down_revision = '9e9513dc80b8'
branch_labels = None
depends_on = None


def upgrade():
    # 기존 문자열 데이터를 JSON 배열로 변환하며 컬럼 타입 변경
    op.execute("""
        UPDATE sw_resources
        SET category = CASE
            WHEN category IS NULL OR category = '' THEN '[]'
            ELSE json_build_array(category)::text
        END
    """)
    op.execute("""
        ALTER TABLE sw_resources
        ALTER COLUMN category TYPE JSON USING category::json
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
