"""Add KPIDashboardCard table

Revision ID: 4d4d39a19f0d
Revises: 08ce5ac029ba
Create Date: 2026-03-11 10:55:26.758632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d4d39a19f0d'
down_revision = '08ce5ac029ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_dashboard_cards',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategories', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('logic', sa.String(length=20), nullable=False),
    sa.Column('selected_perf_keys', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_dashboard_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_dashboard_cards_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_dashboard_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_dashboard_cards_year'))

    op.drop_table('kpi_dashboard_cards')
    # ### end Alembic commands ###
