"""Add year column to meeting_sessions

Revision ID: 4e89f2be560a
Revises: 871549a19cee
Create Date: 2025-12-08 19:08:37.257999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e89f2be560a'
down_revision = '871549a19cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_group_session'), type_='unique')
        batch_op.create_unique_constraint('unique_group_year_session', ['group_id', 'year', 'session_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_group_year_session', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_group_session'), ['group_id', 'session_number'])
        batch_op.drop_column('year')

    # ### end Alembic commands ###
