"""add product_family to dt_reference_tasks

Revision ID: 53b8997af437
Revises: b4530db1743c
Create Date: 2026-02-20 22:20:54.844608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b8997af437'
down_revision = 'b4530db1743c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_reference_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_family', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_reference_tasks', schema=None) as batch_op:
        batch_op.drop_column('product_family')

    # ### end Alembic commands ###
