"""Add office attachments table

Revision ID: 59910f10c626
Revises: 07e163bcb543
Create Date: 2025-12-04 01:29:15.946044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59910f10c626'
down_revision = '07e163bcb543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_attachments',
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['office_agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_attachments')
    # ### end Alembic commands ###
