"""strategy assessment per division

Revision ID: 5e9bcac5ad3d
Revises: 001d51d7135f
Create Date: 2026-08-14 15:27:03.468337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9bcac5ad3d'
down_revision = '001d51d7135f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 자동 생성이 여기서도 dt2_agent_runs 인덱스 삭제를 넣었으나 제거했다.
    # 이 마이그레이션과 무관한 기존 드리프트다(앞 리비전 주석 참고).
    #
    # 진단 단위가 전사 통합에서 사업부별로 바뀐다. 기존 행에는 대응하는 사업부가
    # 없으므로 NOT NULL 컬럼을 바로 붙일 수 없다. 세 걸음으로 나눈다.
    conn = op.get_bind()

    # 1) 우선 nullable 로 추가한다.
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_assessment_plan_dimension'), type_='unique')

    # 2) 옛 행을 정리한다.
    #    값이 하나도 없는 행은 전략 생성 시 자동으로 만들어진 빈 칸이라 지워도
    #    잃을 것이 없다. 새 구조에서 사업부별로 다시 만들어진다.
    conn.execute(sa.text("""
        DELETE FROM strategy_assessment
        WHERE division_id IS NULL
          AND current_level IS NULL
          AND target_level IS NULL
          AND (note IS NULL OR note = '')
    """))

    #    입력값이 있는 행이 남아 있다면 사람이 매긴 판단이므로 버리지 않는다.
    #    어느 사업부인지 알 수 없으니 첫 사업부로 옮기고, 확인하도록 메모를 남긴다.
    fallback = conn.execute(sa.text("""
        SELECT id FROM divisions
        WHERE is_active = true AND is_kpi_owner = true
        ORDER BY "order", id LIMIT 1
    """)).scalar()
    if fallback is not None:
        conn.execute(sa.text("""
            UPDATE strategy_assessment
            SET division_id = :fallback,
                note = COALESCE(note || ' ', '') || '[이관] 사업부별 진단으로 바뀌기 전 입력값입니다. 사업부를 확인하세요.'
            WHERE division_id IS NULL
        """), {'fallback': fallback})

    #    사업부 자체가 없는 환경이면 옮길 곳이 없다. 값 있는 행이 남았다면
    #    조용히 지우지 말고 멈춘다.
    left = conn.execute(sa.text(
        'SELECT count(*) FROM strategy_assessment WHERE division_id IS NULL'
    )).scalar()
    if left:
        raise RuntimeError(
            f'division_id 를 채우지 못한 진단 {left}건이 있습니다. '
            '활성 KPI 사업부가 없는 환경입니다. 사업부 설정 후 다시 시도하세요.'
        )

    # 3) 이제 NOT NULL 로 조인다.
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.alter_column('division_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index(batch_op.f('ix_strategy_assessment_division_id'), ['division_id'], unique=False)
        batch_op.create_unique_constraint('uq_assessment_plan_division_dimension', ['plan_id', 'division_id', 'dimension'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_plan_division_dimension', type_='unique')
        batch_op.drop_index(batch_op.f('ix_strategy_assessment_division_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_assessment_plan_dimension'), ['plan_id', 'dimension'])
        batch_op.drop_column('division_id')

    # ### end Alembic commands ###
