"""Add user_id and is_public to process_diagram_data

Revision ID: 662c3d2e4b43
Revises: 3d21164fd6d0
Create Date: 2025-12-08 11:11:25.157576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662c3d2e4b43'
down_revision = '3d21164fd6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_diagram_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # 기존 데이터의 is_public을 True로 설정 (공용으로 표시)
    # PostgreSQL은 Boolean 타입에 TRUE/FALSE 사용
    op.execute("UPDATE process_diagram_data SET is_public = TRUE WHERE is_public IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_diagram_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_public')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
