"""Add graph_heights to tech_level_data

Revision ID: 665cc46dc748
Revises: 4212dfd4fc3a
Create Date: 2025-12-21 18:54:22.002843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '665cc46dc748'
down_revision = '4212dfd4fc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_heights', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.drop_column('graph_heights')

    # ### end Alembic commands ###
