"""link solutions to the projects that deliver them

Revision ID: 68051f7f2767
Revises: 9b649b6f578d
Create Date: 2026-08-17 11:09:43.030808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68051f7f2767'
down_revision = '9b649b6f578d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        # NOT NULL 인데 server_default 가 없으면 이미 있는 행에서 터진다.
        batch_op.add_column(sa.Column(
            'project_uuids', postgresql.JSON(astext_type=sa.Text()),
            nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        batch_op.drop_column('project_uuids')

    # ### end Alembic commands ###
