"""add survey tables

Revision ID: 6e4d7588e875
Revises: b71ac3ed145b
Create Date: 2026-08-15 02:46:46.274639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e4d7588e875'
down_revision = 'b71ac3ed145b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_refs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_plan_id'), ['plan_id'], unique=False)

    op.create_table('survey_access_log',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_access_log_survey_id'), ['survey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_access_log_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('survey_question',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('qtype', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('link_category', sa.String(length=20), nullable=True),
    sa.Column('link_dimension', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_question_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_response',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('division_source', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'user_id', name='uq_survey_response_user')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_response_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_survey_id'), ['survey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_user_id'), ['user_id'], unique=False)

    op.create_table('survey_answer',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_answer_response_question')
    )
    with op.batch_alter_table('survey_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_answer_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_answer_response_id'))
        batch_op.drop_index(batch_op.f('ix_survey_answer_question_id'))

    op.drop_table('survey_answer')
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_response_user_id'))
        batch_op.drop_index(batch_op.f('ix_survey_response_survey_id'))
        batch_op.drop_index(batch_op.f('ix_survey_response_division_id'))

    op.drop_table('survey_response')
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_question_survey_id'))

    op.drop_table('survey_question')
    with op.batch_alter_table('survey_access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_access_log_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_survey_access_log_survey_id'))

    op.drop_table('survey_access_log')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_plan_id'))

    op.drop_table('survey')
    # ### end Alembic commands ###
