"""add linked_id to report_plan_items

Revision ID: 71bccfd8dd56
Revises: fce35ad4b4cc
Create Date: 2026-03-18 20:06:06.159966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bccfd8dd56'
down_revision = 'fce35ad4b4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_plan_items', schema=None) as batch_op:
        batch_op.drop_column('linked_id')

    # ### end Alembic commands ###
