"""dt2_agent_runs for agent trace diagnosis

Revision ID: 7f09ca9b297c
Revises: b83c0e5a4f12
Create Date: 2026-08-08 03:09:18.450756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f09ca9b297c'
down_revision = 'b83c0e5a4f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt2_agent_runs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hops', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('readonly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('verdict_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt2_agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_agent_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_agent_runs_verdict'), ['verdict'], unique=False)
        # 조회는 늘 '최근 것부터' 다 — 진단용이라 옛것을 훑을 일이 없다
        batch_op.create_index(batch_op.f('ix_dt2_agent_runs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt2_agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_dt2_agent_runs_verdict'))
        batch_op.drop_index(batch_op.f('ix_dt2_agent_runs_user_id'))

    op.drop_table('dt2_agent_runs')
    # ### end Alembic commands ###
