"""Add spdm_modules and spdm_spec_key_suggestions

Revision ID: 81f93d9c46e6
Revises: 97fae0e7fae2
Create Date: 2026-02-11 13:37:22.061772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81f93d9c46e6'
down_revision = '97fae0e7fae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spdm_modules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('division_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specs', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spdm_spec_key_suggestions',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spdm_spec_key_suggestions')
    op.drop_table('spdm_modules')
    # ### end Alembic commands ###
