"""add strategy_element for the analysis stage

Revision ID: 85c527c0b038
Revises: 8d7ac2537dca
Create Date: 2026-08-16 22:28:23.904186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c527c0b038'
down_revision = '8d7ac2537dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_element',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=1), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_element', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_element_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_element_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_element', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_element_plan_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_element_division_id'))

    op.drop_table('strategy_element')
    # ### end Alembic commands ###
