"""add personal_access_tokens for MCP

Revision ID: 860bcaf47aa8
Revises: e2c73f8a15b6
Create Date: 2026-08-01 01:31:47.228350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860bcaf47aa8'
down_revision = 'e2c73f8a15b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_access_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_access_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_personal_access_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_access_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_personal_access_tokens_token_hash'))

    op.drop_table('personal_access_tokens')
    # ### end Alembic commands ###
