"""Add KPI and KPICategory tables

Revision ID: 8d4254b0549d
Revises: b30fbd45eff9
Create Date: 2026-01-10 08:49:15.592162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d4254b0549d'
down_revision = 'b30fbd45eff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('bg_color', sa.String(length=20), nullable=True),
    sa.Column('hover_color', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_categories_year'), ['year'], unique=False)

    op.create_table('kpis',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('kpi_type', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('monthly_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('green_threshold', sa.Integer(), nullable=True),
    sa.Column('yellow_threshold', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kpi_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpis_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpis_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpis_year'))
        batch_op.drop_index(batch_op.f('ix_kpis_category_id'))

    op.drop_table('kpis')
    with op.batch_alter_table('kpi_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_categories_year'))

    op.drop_table('kpi_categories')
    # ### end Alembic commands ###
