"""record how a survey respondent role was determined

Revision ID: 8d7ac2537dca
Revises: c691452a8cae
Create Date: 2026-08-15 21:44:31.270672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7ac2537dca'
down_revision = 'c691452a8cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_source', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('role_source')

    # ### end Alembic commands ###
