"""add strategy_document for the planning stage

Revision ID: 9b649b6f578d
Revises: fc99fafc486e
Create Date: 2026-08-17 10:18:04.319168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b649b6f578d'
down_revision = 'fc99fafc486e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_document',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_document_plan_id'), ['plan_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_document_plan_id'))

    op.drop_table('strategy_document')
    # ### end Alembic commands ###
