"""add sw_resources table

Revision ID: 9e9513dc80b8
Revises: b50db2f81a06
Create Date: 2026-03-23 20:40:41.715048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9513dc80b8'
down_revision = 'b50db2f81a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sw_resources',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('vendor', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('license_count', sa.Integer(), nullable=True),
    sa.Column('license_unit', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sw_resources')
    # ### end Alembic commands ###
