"""add link_system to spdm_modules

Revision ID: a6d233565613
Revises: aaeec7814e9e
Create Date: 2026-02-11 16:04:42.686960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d233565613'
down_revision = 'aaeec7814e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_system', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.drop_column('link_system')

    # ### end Alembic commands ###
