"""strategy diagnosis: organization axis and metric targets

Revision ID: a93481c77974
Revises: 5e9bcac5ad3d
Create Date: 2026-08-14 15:43:11.109476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93481c77974'
down_revision = '5e9bcac5ad3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_metric_target',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'division_id', 'metric_key', name='uq_metric_target_plan_division_key')
    )
    with op.batch_alter_table('strategy_metric_target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_metric_target_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_metric_target_plan_id'), ['plan_id'], unique=False)

    # 자동 생성이 여기서도 dt2_agent_runs 인덱스 삭제를 넣었으나 제거했다.
    # 이 마이그레이션과 무관한 기존 드리프트다(앞 리비전 주석 참고).
    #
    # category 도 NOT NULL 이라 기존 행이 있으면 바로 붙일 수 없다. 기존 행은
    # 전부 기술 성숙도였으므로 그 값으로 채운 뒤 조인다.
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_assessment_plan_division_dimension'), type_='unique')

    op.get_bind().execute(sa.text(
        "UPDATE strategy_assessment SET category = 'technical' WHERE category IS NULL"
    ))

    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.alter_column('category', existing_type=sa.String(length=20), nullable=False)
        batch_op.create_unique_constraint('uq_assessment_plan_division_category_dimension', ['plan_id', 'division_id', 'category', 'dimension'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_assessment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_plan_division_category_dimension', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_assessment_plan_division_dimension'), ['plan_id', 'division_id', 'dimension'])
        batch_op.drop_column('category')

    with op.batch_alter_table('strategy_metric_target', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_metric_target_plan_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_metric_target_division_id'))

    op.drop_table('strategy_metric_target')
    # ### end Alembic commands ###
