"""add is_linked and link_method to spdm_modules

Revision ID: aaeec7814e9e
Revises: 178a6dd05474
Create Date: 2026-02-11 15:33:41.515097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaeec7814e9e'
down_revision = '178a6dd05474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_linked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('link_method', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spdm_modules', schema=None) as batch_op:
        batch_op.drop_column('link_method')
        batch_op.drop_column('is_linked')

    # ### end Alembic commands ###
