"""Add equipment_location to test_methods

Revision ID: b30fbd45eff9
Revises: 2b6231034a01
Create Date: 2026-01-05 02:00:27.486353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30fbd45eff9'
down_revision = '2b6231034a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_location', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_methods', schema=None) as batch_op:
        batch_op.drop_column('equipment_location')

    # ### end Alembic commands ###
