"""Change ReportPlanComment is_resolved to status

Revision ID: b50db2f81a06
Revises: e9b690e08977
Create Date: 2026-03-23 20:28:10.163163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50db2f81a06'
down_revision = 'e9b690e08977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_plan_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('is_resolved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_plan_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
