"""Add card_graph_zoom_pan to tech_level_data

Revision ID: b775b8011570
Revises: c27469cc61ba
Create Date: 2025-12-21 19:19:20.367794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b775b8011570'
down_revision = 'c27469cc61ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_graph_zoom_pan', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.drop_column('card_graph_zoom_pan')

    # ### end Alembic commands ###
