"""Add KPI records and targets tables

Revision ID: b7fbe3bc113d
Revises: 705e7d922c38
Create Date: 2026-03-26 19:46:45.429300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fbe3bc113d'
down_revision = '705e7d922c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_records',
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('kpi', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('base_date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_targets',
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kpi', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division', 'year', 'kpi', 'period', name='uq_kpi_target')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_targets')
    op.drop_table('kpi_records')
    # ### end Alembic commands ###
