"""Add graph_view_state to tech_level_data

Revision ID: c27469cc61ba
Revises: 665cc46dc748
Create Date: 2025-12-21 19:11:04.809765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c27469cc61ba'
down_revision = '665cc46dc748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_view_state', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_level_data', schema=None) as batch_op:
        batch_op.drop_column('graph_view_state')

    # ### end Alembic commands ###
