"""drop the unused strategy_evidence table

Revision ID: c539faffd12c
Revises: 68051f7f2767
Create Date: 2026-08-17 12:52:22.747518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c539faffd12c'
down_revision = '68051f7f2767'
branch_labels = None
depends_on = None


def upgrade():
    """안 쓰는 표를 지운다.

    Phase 1 에 만들어 놓고 **한 번도 쓰지 않았다.** 원래 목적이던 「근거 시점
    스냅샷」은 이미 다른 것들이 하고 있다 — 확정본은 `strategy_document.snapshot`
    이, 설문 근거는 볼 때마다 계산이. 남겨 두면 다음 사람이 그게 쓰이는 줄 알고
    거기에 맞춰 짠다.

    ⚠️ **비었는지 먼저 본다.** 쓰는 코드가 없으니 비어 있는 것이 맞지만,
       "맞을 것이다"로 남의 데이터를 지우지 않는다. 행이 있으면 여기서 멈추고,
       그때는 사람이 무엇이 들어갔는지 보고 정한다.
    """
    rows = op.get_bind().execute(
        sa.text('SELECT COUNT(*) FROM strategy_evidence')).scalar()
    if rows:
        raise RuntimeError(
            f'strategy_evidence 에 {rows}행이 있습니다. 쓰는 코드가 없는데 '
            f'데이터가 있다는 뜻이니, 지우기 전에 내용을 확인하세요.')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_target'))
        batch_op.drop_index(batch_op.f('ix_strategy_evidence_plan_id'))

    op.drop_table('strategy_evidence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_evidence',
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_module', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_ref', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('source_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], name=op.f('strategy_evidence_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_evidence_pkey'))
    )
    with op.batch_alter_table('strategy_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_evidence_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_target'), ['target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###
