"""add copy_count to sw_resources

Revision ID: c96435410d5d
Revises: ef2be6b7ad79
Create Date: 2026-03-23 21:35:56.342742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96435410d5d'
down_revision = 'ef2be6b7ad79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copy_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.drop_column('copy_count')

    # ### end Alembic commands ###
