"""Add ProjectAttachment table

Revision ID: cc39fc7ad7e1
Revises: f29b0fe302ff
Create Date: 2025-12-07 05:16:37.898567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc39fc7ad7e1'
down_revision = 'f29b0fe302ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_attachments',
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_attachments_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_attachments_project_id'))

    op.drop_table('project_attachments')
    # ### end Alembic commands ###
