"""add strategy crux

Revision ID: cc9f0d26ff10
Revises: a93481c77974
Create Date: 2026-08-14 15:59:36.022245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9f0d26ff10'
down_revision = 'a93481c77974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_crux',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('source_finding', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_crux', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_crux_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_crux_plan_id'), ['plan_id'], unique=False)

    # 자동 생성이 또 dt2_agent_runs 인덱스 삭제를 넣었으나 제거했다.
    # 이 마이그레이션과 무관한 기존 드리프트다(앞 리비전 주석 참고).
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_crux', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_crux_plan_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_crux_division_id'))

    op.drop_table('strategy_crux')
    # ### end Alembic commands ###
