"""add strategy_solution for the TOWS stage

Revision ID: ddad77df6380
Revises: 85c527c0b038
Create Date: 2026-08-17 08:26:27.922432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddad77df6380'
down_revision = '85c527c0b038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_solution',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('tows', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('element_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_solution_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_solution_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_solution_plan_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_solution_division_id'))

    op.drop_table('strategy_solution')
    # ### end Alembic commands ###
