"""Add ProcessDiagramData table

Revision ID: e5f1df92778d
Revises: 92b5e89500e8
Create Date: 2025-12-02 00:15:25.848041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5f1df92778d'
down_revision = '92b5e89500e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_diagram_data',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('viewport', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('diagram_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_diagram_data')
    # ### end Alembic commands ###
