"""add dt_report_images table

Revision ID: e707bfa26eeb
Revises: d8e2c4f51a93
Create Date: 2026-07-28 18:05:05.016151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e707bfa26eeb'
down_revision = 'd8e2c4f51a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_report_images',
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt_report_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt_report_images_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt_report_images_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt_report_images_slot'), ['slot'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_report_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt_report_images_slot'))
        batch_op.drop_index(batch_op.f('ix_dt_report_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_dt_report_images_project_id'))

    op.drop_table('dt_report_images')
    # ### end Alembic commands ###
