"""add report_plan_meta table

Revision ID: e92ca4dc8bcd
Revises: 71bccfd8dd56
Create Date: 2026-03-18 20:20:08.905304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92ca4dc8bcd'
down_revision = '71bccfd8dd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_plan_meta',
    sa.Column('tab_key', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tab_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_plan_meta')
    # ### end Alembic commands ###
