"""add using_departments to sw_resources

Revision ID: ef2be6b7ad79
Revises: 4c7916eece9a
Create Date: 2026-03-23 21:04:17.481298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2be6b7ad79'
down_revision = '4c7916eece9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('using_departments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_resources', schema=None) as batch_op:
        batch_op.drop_column('using_departments')

    # ### end Alembic commands ###
