"""Add is_public to dx_graphs

Revision ID: f29b0fe302ff
Revises: 77b9642b22a0
Create Date: 2025-12-06 21:40:05.534187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29b0fe302ff'
down_revision = '77b9642b22a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dx_graphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dx_graphs', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
