"""add strategy_gate for the AX-5R stage gate

Revision ID: f2a5f097d1a5
Revises: ddad77df6380
Create Date: 2026-08-17 08:40:10.529688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a5f097d1a5'
down_revision = 'ddad77df6380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_gate',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('gate', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['strategy_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'gate', name='uq_strategy_gate_target')
    )
    with op.batch_alter_table('strategy_gate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_gate_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index('ix_strategy_gate_target', ['target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_gate', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_gate_target')
        batch_op.drop_index(batch_op.f('ix_strategy_gate_plan_id'))

    op.drop_table('strategy_gate')
    # ### end Alembic commands ###
