"""Add unit column to performance_subcategories

Revision ID: f4de7bc4888b
Revises: 446120e8ec3a
Create Date: 2025-12-08 17:29:08.423676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4de7bc4888b'
down_revision = '446120e8ec3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_subcategories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_subcategories', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
