"""Add test_methods table

Revision ID: f8a57966cc0d
Revises: a6f5772c71fc
Create Date: 2026-01-04 19:42:02.047991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a57966cc0d'
down_revision = 'a6f5772c71fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_methods',
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_methods')
    # ### end Alembic commands ###
