"""add dt2 normalized tables (Phase 2)

Revision ID: fba9e7125df9
Revises: e707bfa26eeb
Create Date: 2026-07-28 22:09:31.151383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fba9e7125df9'
down_revision = 'e707bfa26eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt2_performances',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Numeric(), nullable=True),
    sa.Column('target_level', sa.Numeric(), nullable=True),
    sa.Column('actual_level', sa.String(length=100), nullable=True),
    sa.Column('monthly_values_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_monthly', sa.Boolean(), nullable=True),
    sa.Column('is_achievement_type', sa.Boolean(), nullable=True),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('action_notes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_status_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation', sa.String(length=200), nullable=True),
    sa.Column('calc_logic_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_calc_logic', sa.Boolean(), nullable=True),
    sa.Column('dt_contribution', sa.String(length=50), nullable=True),
    sa.Column('has_dt_contribution', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legacy_uuid', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_from_sample', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_raw', sa.String(length=50), nullable=True),
    sa.Column('deleted_by_name', sa.String(length=100), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt2_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_performances_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_performances_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_performances_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_performances_legacy_uuid'), ['legacy_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_performances_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dt2_performances_year'), ['year'], unique=False)

    op.create_table('dt2_projects',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('process', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_poc', sa.Boolean(), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=True),
    sa.Column('is_division_public', sa.Boolean(), nullable=True),
    sa.Column('pl_name', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('dept_name', sa.String(length=200), nullable=True),
    sa.Column('member_names', sa.String(length=500), nullable=True),
    sa.Column('owners_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('members_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_progress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_overview_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_background_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_goal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detail_completed', sa.Boolean(), nullable=True),
    sa.Column('image_group1_category', sa.String(length=50), nullable=True),
    sa.Column('image_group2_category', sa.String(length=50), nullable=True),
    sa.Column('image_refs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_confirmation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_raw', sa.String(length=50), nullable=True),
    sa.Column('deleted_by_name', sa.String(length=100), nullable=True),
    sa.Column('is_permanently_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('permanently_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('permanently_deleted_by_raw', sa.String(length=50), nullable=True),
    sa.Column('permanently_deleted_by_name', sa.String(length=100), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt2_projects', schema=None) as batch_op:
        batch_op.create_index('ix_dt2_projects_active', ['is_deleted', 'is_permanently_deleted', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_is_permanently_deleted'), ['is_permanently_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_projects_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_dt2_projects_year'), ['year'], unique=False)

    op.create_table('dt2_change_proposals',
    sa.Column('project_uuid', sa.String(length=64), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.Integer(), nullable=True),
    sa.Column('on_behalf_of', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['on_behalf_of'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['dt2_projects.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt2_change_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_change_proposals_project_uuid'), ['project_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_change_proposals_status'), ['status'], unique=False)

    op.create_table('dt2_project_attachments',
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('project_uuid', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['dt2_projects.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt2_project_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_project_attachments_legacy_id'), ['legacy_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dt2_project_attachments_project_uuid'), ['project_uuid'], unique=False)

    op.create_table('dt2_project_dependencies',
    sa.Column('project_uuid', sa.String(length=64), nullable=False),
    sa.Column('depends_on_uuid', sa.String(length=64), nullable=False),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['dt2_projects.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_uuid', 'depends_on_uuid', name='uq_dt2_proj_dep')
    )
    with op.batch_alter_table('dt2_project_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_project_dependencies_depends_on_uuid'), ['depends_on_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_project_dependencies_project_uuid'), ['project_uuid'], unique=False)

    op.create_table('dt2_project_editors',
    sa.Column('project_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['dt2_projects.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_uuid', 'user_id', name='uq_dt2_proj_editor')
    )
    with op.batch_alter_table('dt2_project_editors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_project_editors_project_uuid'), ['project_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_project_editors_user_id'), ['user_id'], unique=False)

    op.create_table('dt2_project_performance',
    sa.Column('project_uuid', sa.String(length=64), nullable=False),
    sa.Column('performance_uuid', sa.String(length=64), nullable=False),
    sa.Column('contribution', sa.String(length=50), nullable=True),
    sa.Column('actual_level', sa.String(length=100), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_uuid'], ['dt2_performances.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_uuid'], ['dt2_projects.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_uuid', 'performance_uuid', name='uq_dt2_proj_perf')
    )
    with op.batch_alter_table('dt2_project_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_project_performance_performance_uuid'), ['performance_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_project_performance_project_uuid'), ['project_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt2_project_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_project_performance_project_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_project_performance_performance_uuid'))

    op.drop_table('dt2_project_performance')
    with op.batch_alter_table('dt2_project_editors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_project_editors_user_id'))
        batch_op.drop_index(batch_op.f('ix_dt2_project_editors_project_uuid'))

    op.drop_table('dt2_project_editors')
    with op.batch_alter_table('dt2_project_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_project_dependencies_project_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_project_dependencies_depends_on_uuid'))

    op.drop_table('dt2_project_dependencies')
    with op.batch_alter_table('dt2_project_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_project_attachments_project_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_project_attachments_legacy_id'))

    op.drop_table('dt2_project_attachments')
    with op.batch_alter_table('dt2_change_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_change_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_dt2_change_proposals_project_uuid'))

    op.drop_table('dt2_change_proposals')
    with op.batch_alter_table('dt2_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_projects_year'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_status'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_is_permanently_deleted'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_division_id'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_division'))
        batch_op.drop_index(batch_op.f('ix_dt2_projects_code'))
        batch_op.drop_index('ix_dt2_projects_active')

    op.drop_table('dt2_projects')
    with op.batch_alter_table('dt2_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_performances_year'))
        batch_op.drop_index(batch_op.f('ix_dt2_performances_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_performances_legacy_uuid'))
        batch_op.drop_index(batch_op.f('ix_dt2_performances_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_dt2_performances_code'))
        batch_op.drop_index(batch_op.f('ix_dt2_performances_category'))

    op.drop_table('dt2_performances')
    # ### end Alembic commands ###
