"""Add is_anonymous to BoardCategory

Revision ID: fbc50a1929a2
Revises: 8d4254b0549d
Create Date: 2026-01-13 09:55:59.478145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc50a1929a2'
down_revision = '8d4254b0549d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_categories', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
