"""Add dt_reference_tasks table

Revision ID: fbcabceb8b8a
Revises: c3a7f1d2e5b8
Create Date: 2026-02-20 15:54:43.251374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcabceb8b8a'
down_revision = 'c3a7f1d2e5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_reference_tasks',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('division_id', sa.String(length=50), nullable=True),
    sa.Column('test_item', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('connected_dt_task', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dt_reference_tasks')
    # ### end Alembic commands ###
