"""add task_management_data table

Revision ID: fc4f7fa4863a
Revises: e8d800b66eb8
Create Date: 2026-04-15 10:06:03.118544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc4f7fa4863a'
down_revision = 'e8d800b66eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    if 'task_management_data' in inspect(bind).get_table_names():
        return
    op.create_table('task_management_data',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('last_modified_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_management_data')
    # ### end Alembic commands ###
