"""add solution impact, feasibility and kpi links

Revision ID: fc99fafc486e
Revises: f2a5f097d1a5
Create Date: 2026-08-17 08:46:11.633366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc99fafc486e'
down_revision = 'f2a5f097d1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feasibility', sa.Integer(), nullable=True))
        # ⚠️ NOT NULL 인데 server_default 가 없으면 **이미 있는 행에서 터진다.**
        #    alembic 이 안 넣어주므로 손으로 넣는다.
        batch_op.add_column(sa.Column(
            'kpi_ids', postgresql.JSON(astext_type=sa.Text()),
            nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_solution', schema=None) as batch_op:
        batch_op.drop_column('kpi_ids')
        batch_op.drop_column('feasibility')
        batch_op.drop_column('impact')

    # ### end Alembic commands ###
