"""dt2_worklist_dismissals for my-work snooze

「내 일」 화면에서 손댈 수 없는 항목(멈춘 과제·이슈 적체 등)을 30일 미뤄두는 표.
**추가만 한다** — 기존 표를 건드리지 않으므로 반입해도 데이터 위험이 없다.

⚠️ 자동생성(`flask db migrate`)이 `ix_dt2_agent_runs_created_at` 을 **지우는 줄**을
   함께 만들었는데 **손으로 지웠다.** 이 작업과 아무 상관이 없고, 그 인덱스는
   에이전트 실행 목록을 최신순으로 뽑는 데 쓴다. 자동생성이 낸 무관한 변경을
   그대로 반입하면 운영에서 조용히 느려진다.
   (BaseModel 의 created_at 인덱스를 알렘빅이 모델 정의에서 못 읽는 탓으로 보인다.
    다음에 이 폴더에서 migrate 를 돌릴 때도 같은 줄이 또 나올 것이다 — 또 지울 것.)

Revision ID: fec0468eb1aa
Revises: 7f09ca9b297c
Create Date: 2026-08-11 21:33:19.373499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec0468eb1aa'
down_revision = '7f09ca9b297c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt2_worklist_dismissals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=200), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=False),
    sa.Column('card', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_key', name='uq_dt2_worklist_user_item')
    )
    with op.batch_alter_table('dt2_worklist_dismissals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt2_worklist_dismissals_until'), ['until'], unique=False)
        batch_op.create_index(batch_op.f('ix_dt2_worklist_dismissals_user_id'), ['user_id'], unique=False)


def downgrade():
    with op.batch_alter_table('dt2_worklist_dismissals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt2_worklist_dismissals_user_id'))
        batch_op.drop_index(batch_op.f('ix_dt2_worklist_dismissals_until'))

    op.drop_table('dt2_worklist_dismissals')
    # ### end Alembic commands ###
